syntax = "proto3";
option java_multiple_files = true;
option java_package = "org.serious.dev.grpc";

message UserRequest {
  int64 id = 1;
}

message PostRequest {
  int64 id = 1;
}

message ReservePostRequest {
  int64 id = 1;
  int64 user_id = 2;
}

message UserResponse {
  int64 id = 1;
  string username = 2;
}

message PostResponse {
  int64 id = 1;
}

message ReservePostResponse {
}

service UserService {
  rpc GetUser(UserRequest) returns (UserResponse);
}

service PostService {
  rpc GetPost (PostRequest) returns (PostResponse);
  rpc ReservePost(ReservePostRequest) returns (ReservePostResponse);
}
